[package]
name = "autoclicker"
version = "0.1.0"
authors = ["Austin Jadlowiec <amj102@pitt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "*"
serde = "1.0.123"
